name: app_agendamento
description: A new Flutter project.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^7.1.1

  dio: ^5.2.0+1
  pretty_dio_logger: ^1.3.1

  get_it: ^7.6.0

  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^7.0.1
  shared_preferences: ^2.0.18
  logger: ^1.2.2

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  equatable: ^2.0.5
  
  firebase_core: ^2.13.1
  firebase_remote_config: ^4.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.3
  
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - .env


